language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv lock -r > requirements.txt
  - touch requirements.txt
  - pip install -r requirements.txt -t .
  - zip -r deploy.zip *
script: true
deploy:
  provider: lambda
  function_name: "holidaybot"
  region: "us-west-2"
  role: "arn:aws:iam::952416174265:role/service-role/holidaybot_execution_role"
  runtime: "python3.6"
  handler_name: "handler"
  zip: deploy.zip
  on:
    repo: rwblickhan/holidaybotpy
    branch: master
